# Generated by Django 5.2.6 on 2025-09-13 01:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(help_text='Current location of the truck', max_length=255)),
                ('pickup_location', models.CharField(help_text='Location where the trip started', max_length=255)),
                ('dropoff_location', models.CharField(help_text='Final destination of the trip', max_length=255)),
                ('cycle_hours', models.DecimalField(decimal_places=2, help_text='Total cycle hours for this trip', max_digits=5)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this trip was created')),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='Location of the stop', max_length=255)),
                ('type', models.CharField(choices=[('pickup', 'Pickup'), ('dropoff', 'Dropoff'), ('fuel', 'Fuel'), ('rest', 'Rest')], help_text='Type of stop', max_length=10)),
                ('start_time', models.DateTimeField(help_text='When the stop started')),
                ('end_time', models.DateTimeField(blank=True, help_text='When the stop ended', null=True)),
                ('trip', models.ForeignKey(help_text='The trip this stop belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='core.trip')),
            ],
            options={
                'verbose_name': 'Stop',
                'verbose_name_plural': 'Stops',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(help_text='Date of the log entry')),
                ('status', models.CharField(choices=[('off', 'Off'), ('sleeper', 'Sleeper'), ('driving', 'Driving'), ('on-duty', 'On-Duty')], help_text='Status during this period', max_length=10)),
                ('start_hour', models.TimeField(help_text='Start time of this status period')),
                ('end_hour', models.TimeField(help_text='End time of this status period')),
                ('location', models.CharField(help_text='Location during this period', max_length=255)),
                ('trip', models.ForeignKey(help_text='The trip this log entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='core.trip')),
            ],
            options={
                'verbose_name': 'Log Entry',
                'verbose_name_plural': 'Log Entries',
                'ordering': ['day', 'start_hour'],
                'unique_together': {('trip', 'day', 'start_hour')},
            },
        ),
    ]
